// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qjeyserver/qjeyserverprob/qjeyserver.proto

package qjeyserver

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("qjeyserver/qjeyserverprob/qjeyserver.proto", fileDescriptor_03728808cef42af0)
}

var fileDescriptor_03728808cef42af0 = []byte{
	// 66 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2a, 0xcc, 0x4a, 0xad,
	0x2c, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xd2, 0x47, 0x30, 0x0b, 0x8a, 0xf2, 0x93, 0x90, 0xb8, 0x7a,
	0x05, 0x45, 0xf9, 0x25, 0xf9, 0x46, 0x3c, 0x5c, 0x5c, 0x81, 0x59, 0xa9, 0x95, 0xc1, 0x60, 0xb1,
	0x24, 0x36, 0xb0, 0xa0, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x37, 0x99, 0xb7, 0x7f, 0x42, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QjeyServerClient is the client API for QjeyServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QjeyServerClient interface {
}

type qjeyServerClient struct {
	cc *grpc.ClientConn
}

func NewQjeyServerClient(cc *grpc.ClientConn) QjeyServerClient {
	return &qjeyServerClient{cc}
}

// QjeyServerServer is the server API for QjeyServer service.
type QjeyServerServer interface {
}

func RegisterQjeyServerServer(s *grpc.Server, srv QjeyServerServer) {
	s.RegisterService(&_QjeyServer_serviceDesc, srv)
}

var _QjeyServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "QjeyServer",
	HandlerType: (*QjeyServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "qjeyserver/qjeyserverprob/qjeyserver.proto",
}
